- name: Create VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ name }}"
    cidr_block: "{{ cidr_block }}"
    region: "{{ reg_name }}"
    state: "{{ state }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: vpc_result
  