- name: Create an ec2 launch template
  community.aws.ec2_launch_template:
    name: "{{ name }}"
    image_id: "{{ ami }}"
    key_name: "{{ key_pair }}"
    instance_type: "{{ inst_flav }}"
    region: "{{ reg_name }}"
    security_group_ids: "{{ sg_result.group_id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: launch
