- hosts: localhost
  gather_facts: no
  vars_files:
      - cred.yml
      - vars.yml
  
  roles:
    - security_group
    # - ec2-instance
    - auto_scaling
   # - rds

# - hosts: ec2_wordpress
#   gather_facts: no
    
#   roles:
#     - wordpress
