- hosts: localhost
  gather_facts: no
  vars_files:
      - cred.yml
      - vars.yml
  
- name: Delete an ec2 launch template
  community.aws.ec2_launch_template:
    name: "my_template"
    state: absent

# - hosts: ec2_wordpress
#   gather_facts: no
    
#   roles:
#     - wordpress
