- hosts: localhost
  gather_facts: no
  vars_files:
      - cred.yml
      - vars.yml
  
  roles:
    - aws_VPC
    - aws_SUBNET
    - aws_INT_gateway
    - aws_vpc_ROUTE_table
    - aws_Security_group
    - aws_EC2_launch_template
    - aws_ELB_classic_lb
    - aws_AutoScaling_group

