- name: Create Subnet 1
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: "{{ cidr1 }}"
    az: "{{ availability_zone_1 }}"
    region: "{{ reg_name }}"
    map_public: true
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags: 
      Name: "{{ name }}"
  register: subnet_result_1

- name: Create Subnet 2
  amazon.aws.ec2_vpc_subnet:
    state: "{{ state }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: "{{ cidr2 }}"
    az: "{{ availability_zone_2 }}"
    region: "{{ reg_name }}"
    map_public: true
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags: 
      Name: "{{ name }}"
  register: subnet_result_2

# - name: Display Subnet Info
#   debug:
#     var: subnet_result_1.subnet.id