- name: Create Security Group
  amazon.aws.ec2_security_group:
    name: "{{ wp_sg_name }}"
    description: WP Security Group
    region: "{{ reg_name }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    state: "{{ state }}"
  register: sg_result

