- amazon.aws.elb_classic_lb:
    name: "{{ name }}"
    state: "{{ state }}"
    region: "{{ reg_name }}"
    security_group_ids: "{{ sg_result.group_id }}"
    subnets:
      - "{{ subnet_result_1.subnet.id }}"
      - "{{ subnet_result_2.subnet.id }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    listeners:
      - protocol: http 
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: True
  register: ELB
