- amazon.aws.autoscaling_group:
    name: "{{ name }}"
    load_balancers: "{{ ELB.elb.name }}"
    availability_zones: "{{ ELB.elb.zones }}"
    launch_template:
      launch_template_name: 'my_template'
    min_size: "{{ min_size }}"
    max_size: "{{ max_size }}"
    desired_capacity: "{{ desired_capacity }}"
    vpc_zone_identifier: "{{ ELB.elb.subnets }}"
    region: "{{ reg_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags:
      - key: TargetGroupName
        value: mytargetgroup
        propagate_at_launch: true
  register: autoscale

- name: Gather information about all instances
  amazon.aws.ec2_instance_info:
    region: "{{ reg_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
  register: instance_info

# - name: Display instance Info
#   debug:
#     var: instance_info.instances[0].public_ip_address
#     var: instance_info.instances[1].public_ip_address

# - name: ADDING HOST OF INSTANCE
#   add_host:
#     name: "{{ instance_info.instances[1].public_ip_address }}"
#     groupname: ec2_wordpress